### PR TITLE
My branch

### PR DESCRIPTION
**Pull request by alexeykolodkin**
removed myName.md file

### CODE REVIEW

**Comment by laurentheirendt** [comment]
Somwething went wrong here ... There are lots of the `Merge pull request ...` commits. Can you try again?

**Comment by alexeykolodkin** [comment]
Hi Laurent! Yes, I have experimented a lot. The last pull request from yesturday night is the correct one, where my name is alright and the extra file called myName.md is removed. What should I do? Are there are any ways to remove other trial pull requests?

**Comment by laurentheirendt** [comment]
You can always close pull requests ... but in this pull request, there are still these `Merge pull request ...` commits that shouldn't be there

**Comment by alexeykolodkin** [comment]
Perhaps, I should I do the following: 
1. Close all pull requests
2. Synchronize my fork (Master, Develop and MyBranch) with main (yours) Develop fork
3. Make a new local clone and do all as we learned in course
4. Push this to MyBranch, and then from MyBranch to your Develop fork

is it correct?

**Comment by laurentheirendt** [comment]
yup, that reads correctly 👍🏼

**Pull request closed without merging**
